on:
  pull_request:

name: Rust

jobs:
  build:
    name: Build Driver
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
          targets: thumbv7em-none-eabihf

      - name: Build
        run: cargo build --all-targets --verbose

      - name: Lint with Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run Tests
        run: cargo test --verbose
